
name: bears_palace_app
description: The Bears Palace Booking App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cool_alert: ^1.0.3
  http: ^0.12.0+2
  introduction_screen: ^1.0.9
  circular_profile_avatar: ^1.0.8
  intl: ^0.17.0
  webview_flutter: 0.3.19+9
  google_maps_flutter: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
